version: '2.3'
services:
  nst-zoo:
    image: nst-base
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app/
    command: tail -f /dev/null  # just run forever
